package com.nazmussakib.investmentcalculator

import android.annotation.SuppressLint
import android.app.DownloadManager
import android.content.Context
import android.content.Intent
import android.net.Uri
import android.os.Build
import android.os.Bundle
import android.os.Environment
import android.print.PrintAttributes
import android.print.PrintDocumentAdapter
import android.print.PrintManager
import android.util.Base64
import android.view.View
import android.webkit.*
import android.widget.Toast
import androidx.activity.OnBackPressedCallback
import androidx.appcompat.app.AppCompatActivity
import androidx.core.view.WindowCompat
import java.io.File
import java.io.FileOutputStream

class MainActivity : AppCompatActivity() {

    private lateinit var webView: WebView

    @SuppressLint("SetJavaScriptEnabled")
    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)

        // Edge-to-edge friendly display
        WindowCompat.setDecorFitsSystemWindows(window, true)

        webView = WebView(this)
        setContentView(webView)

        configureWebView()

        // Handle Android hardware/gesture back press
        onBackPressedDispatcher.addCallback(this, object : OnBackPressedCallback(true) {
            override fun handleOnBackPressed() {
                if (webView.canGoBack()) {
                    webView.goBack()
                } else {
                    isEnabled = false
                    onBackPressedDispatcher.onBackPressed()
                }
            }
        })

        // Load app from local bundled assets
        webView.loadUrl("file:///android_asset/index.html")
    }

    @SuppressLint("SetJavaScriptEnabled")
    private fun configureWebView() {
        val settings = webView.settings
        settings.javaScriptEnabled = true
        settings.domStorageEnabled = true
        settings.databaseEnabled = true
        settings.allowFileAccess = true
        settings.allowContentAccess = true
        settings.loadWithOverviewMode = true
        settings.useWideViewPort = true
        settings.setSupportZoom(false)
        settings.cacheMode = WebSettings.LOAD_DEFAULT

        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.O) {
            settings.safeBrowsingEnabled = false
        }

        webView.webViewClient = object : WebViewClient() {
            override fun shouldOverrideUrlLoading(view: WebView?, request: WebResourceRequest?): Boolean {
                val url = request?.url?.toString() ?: return false
                if (url.startsWith("file://") || url.startsWith("http://localhost")) {
                    return false
                }
                // External links open in default Android browser
                try {
                    val intent = Intent(Intent.ACTION_VIEW, Uri.parse(url))
                    startActivity(intent)
                    return true
                } catch (e: Exception) {
                    return false
                }
            }
        }

        webView.webChromeClient = object : WebChromeClient() {
            override fun onConsoleMessage(message: ConsoleMessage?): Boolean {
                return super.onConsoleMessage(message)
            }
        }

        // Native Android PDF & file download handling
        webView.setDownloadListener { url, userAgent, contentDisposition, mimetype, _ ->
            handleDownload(url, mimetype)
        }
    }

    private fun handleDownload(url: String, mimetype: String) {
        try {
            if (url.startsWith("data:")) {
                // Base64 Data URL (e.g. PDF generated by jsPDF)
                val base64Data = url.substringAfter(",")
                val pdfBytes = Base64.decode(base64Data, Base64.DEFAULT)
                val filename = "Nazmus_Sakib_Investment_Projection_${System.currentTimeMillis()}.pdf"

                val downloadsDir = Environment.getExternalStoragePublicDirectory(Environment.DIRECTORY_DOWNLOADS)
                val file = File(downloadsDir, filename)
                FileOutputStream(file).use { it.write(pdfBytes) }

                Toast.makeText(this, "Saved to Downloads: $filename", Toast.LENGTH_LONG).show()
            } else if (url.startsWith("blob:")) {
                // Trigger print dialog as reliable fallback for blob
                printCurrentPage()
            } else {
                val request = DownloadManager.Request(Uri.parse(url))
                request.setMimeType(mimetype)
                request.setNotificationVisibility(DownloadManager.Request.VISIBILITY_VISIBLE_NOTIFY_COMPLETED)
                request.setDestinationInExternalPublicDir(Environment.DIRECTORY_DOWNLOADS, "Investment_Report.pdf")
                val dm = getSystemService(Context.DOWNLOAD_SERVICE) as DownloadManager
                dm.enqueue(request)
                Toast.makeText(this, "Downloading PDF...", Toast.LENGTH_SHORT).show()
            }
        } catch (e: Exception) {
            printCurrentPage()
        }
    }

    private fun printCurrentPage() {
        val printManager = getSystemService(Context.PRINT_SERVICE) as? PrintManager ?: return
        val printAdapter: PrintDocumentAdapter = webView.createPrintDocumentAdapter("Investment Calculator Report")
        val jobName = "${getString(R.string.app_name)} Report"
        printManager.print(jobName, printAdapter, PrintAttributes.Builder().build())
    }
}
